mdapi/src/objects/Category__c.object
<CustomObject>
    <fields>
        <fullName>Reimbursable_Percentage__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Reimbursable Percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Expense Category</label>
    <nameField>
        <label>Expense Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expense Categories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Category__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Preset expense category options</description>
    <label>Expense Category</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Meals</fullName>
            </value>
            <value>
                <fullName>Housing</fullName>
            </value>
            <value>
                <fullName>Auto lease</fullName>
            </value>
            <value>
                <fullName>Auto insurance</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Travel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Category__c/fields/Expense_Item__c.field-meta.xml
<CustomField>
    <fullName>Expense_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Expense Item</label>
    <referenceTo>Expense_Item__c</referenceTo>
    <relationshipLabel>Expense Categories</relationshipLabel>
    <relationshipName>Expense_Categories</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapi/src/objects/Expense_Item__c.object
<CustomObject>
    <label>Expense Item</label>
    <nameField>
        <label>Expense Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expense Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Expense_Report__c</fullName>
        <label>Expense Report</label>
        <referenceTo>Expense_Report__c</referenceTo>
        <relationshipLabel>Expense Items</relationshipLabel>
        <relationshipName>Expense_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Expense_Item__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Expense_Item__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Category</label>
    <referenceTo>Category__c</referenceTo>
    <relationshipLabel>Expense Items</relationshipLabel>
    <relationshipName>Expense_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_Item__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>JPY</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>CAD</fullName>
            </value>
            <value>
                <fullName>CHF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense_Item__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Expense_Item__c/fields/Exchange_Rate__c.field-meta.xml
<CustomField>
    <fullName>Exchange_Rate__c</fullName>
    <label>Exchange Rate</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Expense_Item__c/fields/Reimbursable_Amount__c.field-meta.xml
<CustomField>
    <fullName>Reimbursable_Amount__c</fullName>
    <description>Foormula</description>
    <label>Reimbursable Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

mdapi/src/objects/Expense_Report__c.object
<CustomObject>
    <label>Expense Report</label>
    <nameField>
        <label>Expense Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expense Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Amount__c</fullName>
        <description>The amount of the expense report</description>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Expense_Report__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD (US$)</fullName>
                <default>true</default>
                <label>USD (US$)</label>
            </value>
            <value>
                <fullName>EUR (€)</fullName>
            </value>
            <value>
                <fullName>JPY (¥)</fullName>
            </value>
            <value>
                <fullName>GBP (£)</fullName>
            </value>
            <value>
                <fullName>AUD (A$)</fullName>
            </value>
            <value>
                <fullName>CAD (C$)</fullName>
            </value>
            <value>
                <fullName>CHF (Fr)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ExpenseItemTriggerTest.cls
@isTest
public class ExpenseItemTriggerTest {
    @isTest
    public static void whenExpenseItemInsertedReimbursableAmountCorrect() {

      // select consultant into user 
      User user = [
          SELECT Id
          FROM User
          WHERE Profile.Name = 'Consultant'
          LIMIT 1
        ];

      // assert user exists
      System.assert(user != null, 'Consultant exists');

      System.runAs(user) {
        // create a new expense report called expenseReport and insert it
        Expense_Report__c itemJPY100 = new Expense_Report__c(
          Name = 'Test Expense Report'
        );

        // get category with reimbursable percent 1 and store in variable reimbursable100
        Category__c reimbursable100 = [
          SELECT Id
          FROM Category__c
          WHERE Reimbursable_Percentage__c = 100
          LIMIT 1
        ];
        // get category with reimbursable percent .5 and store in variable reimbursable50
        Category__c reimbursable50 = [
          SELECT Id
          FROM Category__c
          WHERE Reimbursable_Percentage__c = 50
          LIMIT 1
        ];

        // instantiate list of expense items to save later
        List<Expense_Item__c> items = new List<Expense_Item__c>();       

        // instantiate a expense item itemJPY100 with currency JPY, category: reimbursable100, amount: 100, date: yesterday
        // Expense_Item__c itemJPY100 = new Expense_Item__c(
        //   Expense_Report__c = expenseReport.Id,
        //   Category__c = reimbursable100.Id,
        //   Description__c = 'JPY 100',
        //   Date__c = System.today() - 1,
        //   Currency__c = 'JPY',
        //   Amount__c = 100
        // );

        // add to list
        // items.add(itemJPY100);

        // instantiate an expense item itemUSD100 with currency USD, category: reimbursable100, amount: 100, date: yesterday
        Expense_Item__c itemUSD100 = new Expense_Item__c(
          // Expense_Report__c = expenseReport.Id,
          Category__c = reimbursable100.Id,
          Description__c = 'USD 100',
          Date__c = System.today() - 1,
          Currency__c = 'USD',
          Amount__c = 100
        );
        // add to list
        items.add(itemUSD100);

        // instantiate an expense item itemJPY50 with currency JPY, category: reimbursable50, amount:100, date: day before yesterday
        Expense_Item__c itemJPY50 = new Expense_Item__c(
          // Expense_Report__c = expenseReport.Id,
          Category__c = reimbursable50.Id,
          Description__c = 'JPY 50',
          Date__c = System.today() - 2,
          Currency__c = 'JPY',
          Amount__c = 100
        );
        // add to list
        items.add(itemJPY50);

        // instantiate an expense item itemUSD50 with currency USD, category: reimbursable50, amount: 100, date: day before yesterday
        Expense_Item__c itemUSD50 = new Expense_Item__c(
          // Expense_Report__c = expenseReport.Id,
          Category__c = reimbursable50.Id,
          Description__c = 'USD 50',
          Date__c = System.today() - 2,
          Currency__c = 'USD',
          Amount__c = 100
        );
        // add to list
        items.add(itemUSD50);

        Test.startTest();
          // insert items
          insert items;
        Test.stopTest();

        // select saved items and data to assert into a map for easy fetching by id
        Map<Id, Expense_Item__c> savedItems = new Map<Id, Expense_Item__c>([
          SELECT Id, Exchange_Rate__c, Reimbursable_Amount__c
          FROM Expense_Item__c
        ]);

        // TODO update test when fx rates are captured
        // get itemJPY100 by Id from the map
        // assert exchange rate is 0
        // System.assertEquals(0, savedItems.get(itemJPY100.Id).Exchange_Rate__c, 'Assert exchange rate is 0');
        // assert reimbursable amount is 0
        System.assertEquals(0, savedItems.get(itemJPY100.Id).Reimbursable_Amount__c, 'Reimbursable amount is 0');
 
        // get itemUSD100 by Id from the map
        // assert exchange rate is 1
        // System.assertEquals(1, savedItems.get(itemUSD100.Id).Exchange_Rate__c, 'Assert exchange rate is 1');
        // assert reimbursable amount is 100
        System.assertEquals(100, savedItems.get(itemUSD100.Id).Reimbursable_Amount__c, 'Reimbursable amount is 100');
 
        // TODO update test when fx rates are captured
        // get itemJPY50 by Id from the map
        // assert exchange rate is 0
        // System.assertEquals(0, savedItems.get(itemJPY50.Id).Exchange_Rate__c, 'Assert exchange rate is 0');
        // assert reimbursable amount is 0
        System.assertEquals(0, savedItems.get(itemJPY50.Id).Reimbursable_Amount__c, 'Reimbursable amount is 0');

        // get itemUSD50 by Id from the map
        // assert exchange rate is 1
        // System.assertEquals(1, savedItems.get(itemUSD50.Id).Exchange_Rate__c, 'Assert exchange rate is 1');
        // assert reimbursable amount is 50
        System.assertEquals(50, savedItems.get(itemUSD50.Id).Reimbursable_Amount__c, 'Reimbursable amount is 50');

      }
    }

    @isTest
    public static void whenExpenseItemUpdatedReimbursableAmountCorrect() {

      // create test to verify when saved expense item is updated to USD from JPY, exchange rate changes from 0 to 1 
      // create test to verify when saved expense item is updated to JPY from USD, exchange rate changes from 1 to 0
      // run as Consultant
     
    }

    @testSetup
    static void makeData() {
        List<Category__c> categories = new List<Category__c>();

        // categories.add(
        //     new Category__c(
        //         Name = 'Gasoline',
        //         Reimbursable_Percentage__c = 100
        //     )
        // );
        // categories.add(
        //     new Category__c(
        //         Name = 'Meals',
        //         Reimbursable_Percentage__c = 50
        //     )
        // );
    
    insert categories;
      
      // setup test 2 categories for each test
      // 100% and 50% reimbursable
      // practice bulkification
      // add categories to list
      // save list

    }
}