mdapi/src/objects/Expense_Report__c.object
<CustomObject>
    <label>Expense Report</label>
    <nameField>
        <label>Expense Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expense Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Amount__c</fullName>
        <description>The amount of the expense report</description>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

mdapi/src/classes/ExpenseReportSharingTest.cls
@isTest
private class ExpenseReportSharingTest {

    @isTest
  static void whenProfileIsFinanceCanGetAllExpenseReports() {

    Expense_Report__c anothers = new Expense_Report__c(
      Name = 'Show me their money',
      Amount__c = 100
    );
    insert anothers;

    User user = [SELECT Id
                FROM User
                WHERE Profile.Name = 'Finance'
                LIMIT 1];
    System.assert(user != null, 'User Exists');

    System.runAs(user) {
      Expense_Report__c mine = new Expense_Report__c(
        Name = 'Show me my money',
        Amount__c = 500
      );
      insert mine;

      Test.startTest();
      List<Expense_Report__c> saved = [
        SELECT Id
        FROM Expense_Report__c
      ];
      Test.stopTest();

      System.assertEquals(2, saved.size(), 'can see all the money');
 
    }
  }

  @isTest
  static void whenProfileIsConsultantCanOnlyGetOwnedExpenseReports() {

    Expense_Report__c anothers = new Expense_Report__c(
      Name = 'Show me the money',
      Amount__c = 100
    );
    insert anothers;

    User user = [SELECT Id
                FROM User
                WHERE Profile.Name = 'Consultant'
                LIMIT 1];
    System.assert(user != null, 'User Exists');

    System.runAs(user) {
      Expense_Report__c mine = new Expense_Report__c(
        Name = 'Show me my money',
        Amount__c = 500
      );
      insert mine;

      Test.startTest();
      List<Expense_Report__c> saved = [
        SELECT Id
        FROM Expense_Report__c
      ];
      Test.stopTest();

      System.assertEquals(1, saved.size(), 'can see all the money');
   
    }
  }
}