mdapi/src/objects/Expense_Item__c.object
<CustomObject>
    <fields>
        <fullName>Expense_Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Expense Category</label>
        <referenceTo>Expense_Category__c</referenceTo>
        <relationshipLabel>Expense Items</relationshipLabel>
        <relationshipName>Expense_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Expense Item</label>
    <nameField>
        <label>Expense Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expense Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense_Item__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Expense_Item__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>JPY</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>CAD</fullName>
            </value>
            <value>
                <fullName>CHF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense_Item__c/fields/Exchange_Rate__c.field-meta.xml
<CustomField>
    <fullName>Exchange_Rate__c</fullName>
    <label>Exchange Rate</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Expense_Item__c/fields/Reimbursable_Amount__c.field-meta.xml
<CustomField>
    <fullName>Reimbursable_Amount__c</fullName>
    <description>Foormula</description>
    <label>Reimbursable Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ExpenseItemTriggerHandler.cls
public class ExpenseItemTriggerHandler extends TriggerHandler {
    public static void AssignExchangeRate(List < Expense_Item__c > expenseItemList) {
        List < Expense_Item__c > itemsToUpdate = new List < Expense_Item__c > ();
        for (Expense_Item__c expenseItem: expenseItemList) {
            if (expenseItem.Currency__c == 'USD') {
                expenseItem.Exchange_Rate__c = 1;
            } else {
                expenseItem.Exchange_Rate__c = 0;
            }
            itemsToUpdate.add(expenseItem);
        }
    }

    public static void CalculateReimbursableAmount(List < Expense_Item__c > itemList) {
        List < Expense_Item__c > listToUpdate = new List < Expense_Item__c > ();
        Map < Id, Expense_Category__c > categories = new Map < Id, Expense_Category__c > ([
            SELECT Id, Reimbursable_Percentage__c
            FROM Expense_Category__c
        ]);
        for (Expense_Item__c expenseItem: itemList) {
            expenseItem.Reimbursable_amount__c = expenseItem.Exchange_Rate__c * itemObj.Amount__c * (categories.get(expenseItem.Expense_Category__c).Reimbursable_Percentage__c / 100);
            listToUpdate.add(expenseItem);
        }
        categories.get(expenseItem.Reimbursable_amount__c);
    }


    private void beforeInsert(List < Expense_Item__c > itemList) {
        AssignExchangeRate(itemList);
        CalculateReimbursableAmount(itemList);
    }

    private void beforeUpdate(List < Expense_Item__c > itemList) {
        AssignExchangeRate(itemList);
        CalculateReimbursableAmount(itemList);
    }

    private void beforeDelete(List < Expense_Item__c > itemList) {
        //Not much going on here... 
    }

    private void afterInsert(List < Expense_Item__c > itemList) {
        //Not much going on here...
    }

    private void afterUpdate(List < Expense_Item__c > itemList) {
        //Not much going on here...
    }

    private void afterDelete(List < Expense_Item__c > itemList) {
        //Not much going on here...
    }
}